### ISSUE TITLE
SPI driver failed to load

### ISSUE THREAD

**Issue by ryantong1** [starfive-tech/freelight-u-sdk#10]
Modifying configuration files：

step：make linux-menuconfig

  Device Drivers -> 
>   < * >SPI support ->
> > < * >User mode SPI device driver support  

After the file modification is successful, recompile and reload kernel file

BeagleV SPI test：
```
# ls /dev/spi*
ls: /dev/spi*: No such file or directory
# lsmod|grep spi
# 
```

**Comment by pdp7** [comment]
I don't see any SPI nodes in the device tree in this sft-riscv-uboot repo:
https://github.com/starfive-tech/sft-riscv-uboot/blob/starfive/arch/riscv/dts/starfive_vic7100_evb.dts

I think it needs the spi2 node like in beagle_uboot-opensbi:
https://github.com/starfive-tech/beagle_uboot-opensbi/blob/starfive/arch/riscv/dts/starfive_vic7100_evb.dts#L488
```

		spi2:spi2@12410000 {
			compatible = "snps,dw-apb-ssi";
			#address-cells = <1>;
			#size-cells = <0>;
			interrupt-parent = <&plic>;
			interrupts = <70>;
			reg = <0x0 0x12410000 0x0 0x10000>;
			clocks = <&ahb2clk>;
			/*num-cs = <1>;
			cs-gpios = <&gpio 0 0>;*/
			spi_dev0: spi@0 {
				compatible = "rohm,dh2228fv";
				spi-max-frequency = <10000000>;
				reg = <0>;
				status = "okay";
			};
		};
```

**Comment by pdp7** [comment]
The Cadence DesignWare SPI driver also needs to be enabled:
```
pdp7@x1:~/dev/starfive/freelight-u-sdk$ grep SPI conf/sdk_210209_defconfig 
CONFIG_SPI=y
CONFIG_SPI_DEBUG=y
CONFIG_SPI_CADENCE=y
CONFIG_SPI_DESIGNWARE=y
CONFIG_SPI_DW_DMA=y
CONFIG_SPI_DW_MMIO=y
CONFIG_SPI_SIFIVE=y
CONFIG_SPI_SPIDEV=y
```
SPI now loads ok:
```
# dmesg |grep spi
[    3.923747] dw_spi_mmio 12410000.spi2: Detected FIFO size: 8 bytes
[    3.930002] dw_spi_mmio 12410000.spi2: DMA init failed
[    3.935487] dw_spi_mmio 12410000.spi2: registered master spi1
[    3.941662] spi spi1.0: setup mode 0, 8 bits/w, 10000000 Hz max --> 0
[    3.948847] dw_spi_mmio 12410000.spi2: registered child spi1.0
```
And spidev exists:
```
# ls -ltar /dev/spidev1.0 
crw-rw----    1 root     root      153,   0 Jan  1 00:00 /dev/spidev1.0
```

**Comment by ryantong1** [comment]
According to the method provided, after modifying the starfive_vic7100_evb.dts and sdk_210209_defconfig files, the recompiled version of SPI can work normally and the issue is closed @pdp7
