### ISSUE TITLE
HDMI&DSI&CSI drivers not ported

### ISSUE THREAD

**Issue by ryantong1** [starfive-tech/freelight-u-sdk#11]
HDMI&DSI&CSI drivers not ported

**Comment by ryantong1** [comment]
This feature is scheduled to be supported on May 14th

**Comment by bith3ad** [comment]
Mainline or something downstream?

**Comment by pdp7** [comment]
@bith3ad This will at first be in the the 5.10 kernel submodule of freelight-u-sdk.  However, StarFive and BeagleBoard.org are committed to push support upstream.

**Comment by kbingham** [comment]
Note that there is already a driver for the cadence CSI-RX in mainline Linux, but the VIN component from the BSP needs to be redesigned to be able to support async subdevices and use the media controller APIs.

The specific version of the Cadence CSI-RX that the mainline driver supports will need to be checked, and any version differences may need to be handled, but otherwise that demonstrates the correct way of abstracting the receiver, and handling sensors through external subdevices.

**Comment by bith3ad** [comment]
Amazing, I will take a look this weekend. Maybe I can support you on this front :)

**Comment by MichaelZhuxx** [comment]
This is a pre-release multimedia subsystem for JH7100, including ALSA, V4L2, Gstreamer, VPU decoding. please refer to [freelight-u-sdk](https://github.com/starfive-tech/freelight-u-sdk/tree/JH7100_starlight_multimedia) and follow the instructions [readme](https://github.com/starfive-tech/freelight-u-sdk/blob/JH7100_starlight_multimedia/README.md) to fetch, build and test it.

Here is the branches:

[opensbi] https://github.com/starfive-tech/opensbi/tree/master 

[u-boot] https://github.com/starfive-tech/u-boot/tree/Fedora_JH7100_upstream_devel Apply alsa, v4l2 etc. to dts 

[kernel] https://github.com/starfive-tech/linux/tree/beaglev-5.13.y_multimedia Add v4l2 for video capture, alsa for audio, drm for display

[buildroot] https://github.com/starfive-tech/sft-riscv-buildroot/tree/starlight_multimedia
* add starfive private packages:
  * v4l2_test: used to test v4l2 device
  * pp_test: used to switch format and resolution for framebuffer framework
  * sf-gst-omx: from gst-omx and compatible with the omx-il library
  * sf-omx-il: starfive openmax il library for VPU hardware decode
  * stfisp_setfile: this is the host build package, used to generate the isp register setting binary for v4l2 framework
  * wave511: this is chip&media decode hardware wave511 vendor code building
 
* add the following gstreamer patch:
  * support gstreamer plugin fbdevsink NV12 format
  * support gst-play take priority to decode h264/h265 with gst-omx plugin

**Comment by kbingham** [comment]
did anything get upstream to the kernel for this? Does it work with the kernel cadence driver?

**Comment by MichaelZhuxx** [comment]
@kbingham yeah, mipi rx&tx controllers are from cadence. so we could use the upstream driver. for others we will upstream then in next generation SoC-JH7110

**Comment by kbingham** [comment]
@MichaelZhuxx Ok, please let me know when any SoC-JH7110 hardware is available.
