### ISSUE TITLE
Bluetooth    -sh: hciconfig: not found

### ISSUE THREAD

**Issue by ryantong1** [starfive-tech/freelight-u-sdk#12]
Modifying configuration files：

STEP1:make buildroot_initramfs-menuconfig

> Target packages  --->
> > Networking applications  --->        

    		[*] bluez-utils 5.x        
    		[*]   build OBEX support        
    		[*]   build CLI client        
    		[*]     install deprecated tool        
    		[*]   build experimental obexd plugin        
    		[*]   build health plugin        
    		[*]   build midi profile        
    		[*]   build nfc plugin        
    		[*]   build sap plugin                                                                              
    		[*] brcm-patchram-plus   

STEP2:Add content to conf/sdk_210209_defconfig file
```
CONFIG_BT=y
CONFIG_BT_RFCOMM=y
CONFIG_BT_RFCOMM_TTY=y
CONFIG_BT_BNEP=y
CONFIG_BT_BNEP_MC_FILTER=y
CONFIG_BT_BNEP_PROTO_FILTER=y
CONFIG_BT_HIDP=y 
CONFIG_BT_HCIUART=y
CONFIG_BT_HCIUART_H4=y
```
STEP3:Recompile and load
```
# hciconfig hci0 up
-sh: hciconfig: not found
```

**Comment by MichaelZhuxx** [comment]
Bluetooth cannot be loaded normally
