### ISSUE TITLE
which Linux defconfig is used by default?

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/freelight-u-sdk#14]
@MichaelZhuxx Is this the kernel config that is being used? 
https://github.com/starfive-tech/sft-riscv-linux-5.10/blob/93604a0a3ecc4ef8efb9d877854f89df2c7208f7/arch/riscv/configs/defconfig

**Comment by MichaelZhuxx** [comment]
https://github.com/starfive-tech/freelight-u-sdk/blob/starfive/conf/sdk_210209_defconfig
