### ISSUE TITLE
mkfs.vfat path is hardcoded and might not be correct on some Linux distros

### ISSUE THREAD

**Issue by Civil** [starfive-tech/freelight-u-sdk#6]
Here:
https://github.com/starfive-tech/freelight-u-sdk/blob/starfive/Makefile#L336
https://github.com/starfive-tech/freelight-u-sdk/blob/starfive/Makefile#L355

mkfs.vfat is hardcoded to be in /sbin, however on some distros (e.x. Gentoo) it might be located in /usr/sbin

I would test on Debian later, but at this moment I think it might be a better idea to either have some auto-detection logic for it or to rely on `/usr/bin/env` to find it.

(on Gentoo replacing that with `/usr/bin/env mkfs.vfat` fixes the problem and I now have image on my hands).

**Comment by pdp7** [comment]
@Civil can you check if #19 fixed this issue for you?

**Comment by Civil** [comment]
Yeah, that fixes the problem, thanks.
